### ISSUE TITLE
Wrong spelling of "vertex" in graphs.cpp

### ISSUE THREAD

**Issue by human37** [evad1n/graphs-cpp#1]
I believe in your comment you called it "fertex" instead of vertex. I would like that changed soon.

**Comment by human37** [comment]
Doesn't work

**Comment by evad1n** [comment]
This issue is not reproducible. Please provide a line number and your system configuration.

- This message was generated by a human

**Comment by evad1n** [comment]
Fix it yourself idiot

**Comment by human37** [comment]
Fix was deprecated in version 1.6.7

**Comment by evad1n** [comment]
You are deprecated
